import './style.css';
import { buildMainUI } from './layouts/ScreenController.js';
import { buildSidebar } from './layouts/Sidebar.js';

const pageContainer = document.querySelector('.page-container');

// buildMainUI();
buildSidebar(pageContainer);

const test = document.createElement('div');
test.textContent = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac bibendum velit. Aenean erat turpis, porttitor a orci quis, consequat elementum purus. Fusce non blandit purus. Etiam non volutpat sem, vitae rhoncus orci. Suspendisse potenti. Sed mauris elit, sagittis quis mi sed, malesuada hendrerit sapien. Aenean pharetra ipsum id volutpat consectetur. Aliquam ut volutpat augue, ut bibendum lectus. Curabitur luctus diam ut est facilisis, vitae eleifend libero varius. Ut magna tortor, consequat vel semper eget, iaculis vel neque. Ut vehicula orci tortor, quis bibendum tortor faucibus sit amet. In sit amet auctor ipsum, nec accumsan urna. Nam facilisis mi sed venenatis finibus. Vivamus blandit hendrerit ultricies.

Quisque nec dui tempor, bibendum elit ultrices, semper metus. Suspendisse blandit, neque nec suscipit lacinia, leo risus aliquam arcu, at fermentum eros enim in diam. Praesent ac hendrerit quam. Praesent dapibus dui quis augue feugiat tincidunt. Nulla accumsan ipsum massa, eu euismod lorem vulputate vitae. Curabitur consequat tempus enim eu efficitur. Vivamus at sapien augue.

Aliquam elit arcu, lacinia sit amet finibus sed, molestie vitae elit. Curabitur non ex porttitor, dictum lectus sed, dictum enim. Nunc porttitor neque dui, ut malesuada sapien iaculis sit amet. Nunc vestibulum dictum tortor sed cursus. Nunc quis magna tellus. Nullam volutpat commodo erat sit amet euismod. Nunc vitae felis libero. Nullam finibus porta lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus dictum pretium. Phasellus placerat, dui eget tempor pretium, velit sapien cursus metus, quis tempus ante leo tincidunt erat. Aliquam erat volutpat.

Curabitur sit amet erat eu enim interdum porta. Sed porta lobortis iaculis. Sed vel enim non urna convallis maximus in sed lectus. Ut ut odio vitae lectus lacinia feugiat. Pellentesque a dolor aliquam, ornare lectus quis, vestibulum ipsum. Integer fringilla diam eget ligula mattis pharetra. Maecenas lacus magna, aliquam at egestas ac, malesuada ac velit. Nunc molestie aliquet urna nec vulputate. Donec ut efficitur tortor. Curabitur hendrerit, erat at gravida sodales, nunc purus semper arcu, blandit laoreet leo quam ut ante. Sed hendrerit cursus risus eu consectetur. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Proin consectetur imperdiet sapien id bibendum. Nulla consectetur lorem vitae nisi rutrum feugiat. Nunc et vehicula velit, aliquam egestas lorem. Nulla cursus eleifend metus quis condimentum. Mauris condimentum fringilla est, id consequat urna lobortis sed. Vestibulum interdum orci orci, at semper quam convallis at. Quisque porttitor mi ut sem maximus dignissim. Proin maximus, lacus eget gravida varius, felis sapien egestas lorem, a laoreet mi neque non dolor. Donec sit amet malesuada tellus.

Cras ut euismod urna, vel posuere urna. Proin dolor nisi, fringilla vel augue non, porta posuere nibh. Duis sodales, lacus ac pulvinar blandit, turpis elit volutpat nulla, id eleifend ligula tortor eget ipsum. Suspendisse posuere suscipit lacus, vitae aliquam elit convallis quis. Sed nibh mi, laoreet id imperdiet vitae, tincidunt eget nisl. Donec fringilla nulla tristique, sagittis neque eget, pulvinar mauris. Integer vestibulum quis lorem ut malesuada. Ut vestibulum dolor ac nisi consectetur, in tincidunt justo ullamcorper.

Etiam efficitur, velit dignissim egestas eleifend, nisi metus mattis velit, a gravida sem turpis in arcu. Donec ut felis ut nisi faucibus sagittis sed in massa. Curabitur vel pretium sapien, vitae interdum tortor. Vestibulum eget libero id dui ornare accumsan et dignissim massa. Donec sem erat, pellentesque ut auctor a, pellentesque eget dolor. Nulla facilisi. Pellentesque feugiat vitae nulla at pulvinar. Ut id lacus sagittis, interdum tellus ut, tincidunt felis. Praesent egestas, augue quis porta cursus, justo massa tincidunt ipsum, eu cursus orci arcu ut risus. Praesent semper magna quis metus ullamcorper malesuada. Donec nec eros a neque commodo placerat ac ac leo. Sed luctus mauris bibendum ipsum tincidunt, quis finibus arcu pulvinar. Donec eu tempor lectus. Integer suscipit rhoncus metus, vitae feugiat erat vehicula eget. Nullam posuere nisl dui, sed fringilla nisl aliquet vel. Aenean vehicula massa non turpis blandit, in aliquet nibh faucibus.

Ut cursus sodales nisl sed consectetur. Suspendisse dui sem, eleifend a ipsum sit amet, gravida feugiat nisl. Etiam ut dignissim magna, sed lacinia turpis. Nulla a nulla ac ipsum facilisis fringilla vel in magna. Ut at faucibus felis. Sed sed porta felis. Phasellus et mauris nec nisl volutpat blandit nec non nulla.

Suspendisse aliquet non justo sed fermentum. Proin scelerisque justo at dolor posuere, ut pharetra tellus lacinia. Vestibulum volutpat varius pulvinar. Fusce at gravida elit. Suspendisse id dictum diam. Phasellus euismod rutrum justo sit amet blandit. Maecenas elementum dolor non placerat auctor. Pellentesque vestibulum consectetur consequat. Proin laoreet sed felis vel interdum. Mauris congue pellentesque varius. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam blandit sit amet neque quis tristique.

Etiam efficitur turpis quis pulvinar aliquam. Integer ac porttitor justo. Ut accumsan magna sapien, eget finibus est sodales a. Nunc sagittis dapibus dui at fermentum. Integer tempor ultricies aliquam. Quisque non mi eget libero rhoncus porta a dictum mi. Curabitur ut velit quam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut ut nunc quis purus iaculis consequat. Pellentesque eros risus, mattis et libero sit amet, consequat placerat eros.

Aliquam erat volutpat. Nam hendrerit pellentesque erat, a posuere nisl vulputate eget. Mauris pulvinar fringilla eleifend. Aliquam sed magna molestie, venenatis nisi nec, rhoncus dolor. Nam non libero tellus. Cras imperdiet nisi in mattis aliquet. Maecenas dui nisi, cursus sed tempus sed, imperdiet eget leo. Integer sed sapien enim. Integer at elit non diam scelerisque pellentesque. Aenean mollis metus at molestie pharetra. Morbi iaculis fringilla bibendum. Aliquam fermentum eu nibh vitae elementum. Nam suscipit sed metus non pharetra. Nullam et lacus massa. Etiam ut ligula vel mauris auctor rutrum.

Donec ut sodales ligula. Donec ante leo, congue ac facilisis sit amet, dignissim vitae nibh. Nullam id sollicitudin nulla. Morbi in ullamcorper est, eu ultrices nunc. Donec pulvinar fermentum lectus in bibendum. Praesent sit amet purus eleifend, feugiat risus ut, luctus nibh. Proin at luctus mi, porttitor ullamcorper mauris. Vestibulum sed tortor vel est volutpat egestas.

Aliquam lectus tortor, finibus in pellentesque ut, auctor vel magna. Nunc pellentesque est sed pulvinar scelerisque. Duis ac volutpat lectus, nec efficitur dui. Nulla nec laoreet urna, at rutrum velit. Maecenas consectetur vel sem non scelerisque. Praesent a dui vitae odio gravida gravida id sit amet velit. Nullam vel risus eget turpis laoreet fringilla. Nunc posuere velit eu velit molestie, id pellentesque orci imperdiet.

Sed vulputate tristique tincidunt. Quisque quis enim sed diam facilisis dictum. Vestibulum eu mauris vestibulum, posuere lectus a, eleifend nisl. Phasellus sollicitudin erat quis auctor venenatis. Nullam hendrerit velit ipsum, sit amet pellentesque nisi bibendum sed. Aliquam tincidunt facilisis accumsan. Integer faucibus massa metus, et ornare ex porta at. In faucibus lorem id vestibulum tincidunt. Vivamus vel tortor egestas ante auctor aliquam at in lorem. Quisque luctus sagittis felis, mattis convallis mauris lobortis nec. Nam vulputate vel libero eget volutpat.

Curabitur non augue ac dolor malesuada faucibus. Morbi id nunc molestie, commodo quam eget, fringilla tortor. Vivamus tempus suscipit magna, sit amet ultrices odio viverra sed. Nam quis laoreet arcu, ac vestibulum libero. Ut lobortis vehicula elementum. Duis convallis ante et quam dictum aliquet. Donec suscipit, nibh eu pellentesque pulvinar, augue nibh tempor velit, vel lacinia sapien ligula non augue. Sed sagittis tincidunt augue, quis tincidunt lacus posuere vitae. Proin quis condimentum dolor. Pellentesque at eros dictum, accumsan orci congue, hendrerit odio. In nec lacinia libero. Donec ac tincidunt libero, id finibus massa. Praesent tristique ut arcu non auctor.

Cras id massa maximus, consectetur quam nec, cursus est. Integer accumsan arcu et tristique pharetra. Pellentesque blandit tempus nulla, sit amet laoreet enim sodales sit amet. Nam risus nisl, fringilla quis blandit nec, vehicula eget lorem. Donec lobortis ante sit amet nisi dignissim, ac pretium lectus laoreet. Suspendisse pharetra ex tempor dolor vestibulum blandit. Integer at dapibus enim. Donec dignissim sed lectus vitae placerat. In consequat est a nulla posuere venenatis. Aenean efficitur aliquet ante, vitae consequat nulla semper a. Integer consequat quam quis mauris euismod, eu tincidunt mi porttitor. Quisque sit amet posuere diam, sed consequat dui. Morbi euismod venenatis nulla sit amet mattis.

Morbi placerat ex sed felis dapibus, vitae fringilla odio rutrum. Phasellus vel ornare diam, vitae rutrum orci. Mauris sed congue diam, et tristique tellus. Nullam ut posuere tellus, pulvinar ornare turpis. Donec porta vel dui sit amet finibus. Maecenas euismod neque ex, id gravida nibh molestie in. Nulla facilisi. Sed consequat facilisis massa, vel ornare sapien eleifend non. Nulla libero neque, lacinia a sollicitudin sit amet, sagittis sit amet erat. Sed id neque in elit ultricies mollis. Praesent elementum eu risus quis auctor. Sed auctor convallis erat quis lacinia. Nam urna justo, tempus et sagittis eu, scelerisque eget turpis. Cras maximus auctor facilisis. Proin imperdiet porta est, eu semper urna volutpat in. Etiam pellentesque vel diam luctus pellentesque.

In ornare odio enim, eget hendrerit metus tincidunt quis. In hac habitasse platea dictumst. Nullam tempus, leo bibendum auctor tincidunt, mauris velit euismod dui, vitae pellentesque velit magna et nulla. Donec hendrerit ipsum ut enim semper ornare. Duis tincidunt suscipit porta. Donec elementum rhoncus dolor, ut consectetur sapien faucibus in. Vivamus at nunc facilisis, vestibulum nulla eu, egestas lectus. Nullam a risus faucibus, egestas lacus non, pretium ligula.

Morbi imperdiet magna risus, at viverra felis semper sed. Pellentesque at quam consequat, faucibus sem eget, blandit lectus. Cras aliquam lectus eget quam iaculis varius. Pellentesque blandit purus et dictum porttitor. Cras id justo ac augue maximus posuere. Nunc scelerisque enim ut justo pulvinar, a pretium urna aliquam. Donec in lorem malesuada, mollis mi nec, convallis arcu. Duis feugiat pellentesque eros, eget ultrices ante dignissim vel. Sed volutpat nisl vel leo mollis convallis ac ut eros. Quisque porta scelerisque condimentum. Aliquam vel felis vel augue dapibus euismod. Mauris maximus ultricies sem consectetur sollicitudin. Pellentesque eu commodo erat.

Morbi vehicula vulputate eros sit amet fringilla. Morbi id iaculis metus, nec lobortis nisi. Integer tempus sit amet odio eget iaculis. Nulla ac dui fermentum, varius velit tincidunt, hendrerit ex. Ut blandit ornare aliquam. Nunc vitae mattis tellus, id blandit nunc. Proin vestibulum tellus in dui lacinia facilisis. Ut sit amet augue dolor.`;
test.style.overflow = 'auto';
pageContainer.appendChild(test);